apiVersion: v1
kind: Service

metadata:
  name: astra-service
  namespace: astra

spec:
  selector:
    app: astra-xdr

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: LoadBalancer
